In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import game2p3s as g

In [3]:
G = g.random_game()

In [4]:
print G

[[[5 1 6]
  [7 4 2]
  [8 9 3]]

 [[4 2 3]
  [5 6 7]
  [8 9 1]]]


In [5]:
G.standard

GameArray([[[9, 3, 8],
        [1, 7, 2],
        [4, 5, 6]],

       [[9, 1, 8],
        [2, 5, 7],
        [6, 4, 3]]])

In [6]:
print G.player(0).standard
print G.standard.player(0)

[[9 3 8]
 [1 7 2]
 [4 5 6]]
[[9 3 8]
 [1 7 2]
 [4 5 6]]


In [7]:
type(G.player(1))

game2p3s.HalfGameArray

In [8]:
G = G.standard

In [9]:
G

GameArray([[[9, 3, 8],
        [1, 7, 2],
        [4, 5, 6]],

       [[9, 1, 8],
        [2, 5, 7],
        [6, 4, 3]]])

In [10]:
hga = g.HalfGameArray(range(1,10))

In [11]:
print hga

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print hga.standard

[[9 7 8]
 [3 5 4]
 [6 2 1]]


In [13]:
hga == hga.standard

True

In [14]:
hgar = g.random_game().player(1)

In [15]:
hgar == hga

False

In [16]:
hgar.standard

HalfGameArray([[9, 8, 4],
       [6, 7, 1],
       [2, 3, 5]])

In [17]:
hga.standard

HalfGameArray([[9, 7, 8],
       [3, 5, 4],
       [6, 2, 1]])

In [18]:
gr = g.random_game()
G = g.GameArray(range(1,10) * 2)

In [19]:
G

GameArray([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
G.standard

GameArray([[[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]],

       [[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]]])

In [21]:
gr == G

False

In [22]:
gr

GameArray([[[1, 4, 2],
        [3, 9, 6],
        [8, 7, 5]],

       [[2, 4, 6],
        [3, 5, 1],
        [7, 8, 9]]])

In [23]:
LAZY_STRATEGY = range(1, 10)

LAZY_STRATEGY_HALF_GAME = g.HalfGameArray(LAZY_STRATEGY)
LAZY_STRATEGY_GAME = g.GameArray(LAZY_STRATEGY * 2)

In [24]:
lazy = LAZY_STRATEGY_GAME.copy()

In [25]:
standard_is = lazy.standard.view(np.ndarray)
standard_is

array([[[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]],

       [[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]]])