In [2]:
import numpy as np

In [3]:
M = np.arange(9) + 1
np.random.shuffle(M)
M = M.reshape((3,3))

In [4]:
print M

[[2 5 4]
 [6 7 3]
 [9 8 1]]


In [5]:
roll_axes_by = np.unravel_index(M.argmax(), (3,3))

In [6]:
for axis, roll_by in enumerate(roll_axes_by):
    if roll_by:
        M = np.roll(M, -roll_by, axis=axis)
print M

[[9 8 1]
 [2 5 4]
 [6 7 3]]


In [7]:
S = M[1:, 1:]
print S

[[5 4]
 [7 3]]


In [8]:
roll_sub_axes_by = np.unravel_index(S.argmax(), (2,2))

In [9]:
for axis, roll_by in enumerate(roll_sub_axes_by):
    if roll_by:
        S = np.roll(S, 1, axis=axis)
M[1:, 1:] = S

In [10]:
print M

[[9 8 1]
 [2 7 3]
 [6 5 4]]


In [11]:
np.argmax(M)

0

In [18]:
for i in range(1,10):
    idxs = np.where(M==i)
    x,y = idxs[0][0], idxs[1][0]
    print M[x,y]

1
2
3
4
5
6
7
8
9
