In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import game2p3s as g

In [3]:
G = g.random_game()

In [4]:
print G

[[[2 4 5]
  [7 6 1]
  [9 3 8]]

 [[6 2 5]
  [8 9 7]
  [1 4 3]]]


In [5]:
G.standard

GameArray([[[9, 3, 8],
        [2, 6, 1],
        [7, 4, 5]],

       [[1, 4, 3],
        [6, 9, 7],
        [8, 2, 5]]])

In [6]:
print G.player(0).standard
print G.standard.player(0)

[[9 3 8]
 [2 6 1]
 [7 4 5]]
[[9 3 8]
 [2 6 1]
 [7 4 5]]


In [7]:
type(G.player(1))

game2p3s.HalfGameArray

In [8]:
G = G.standard

In [9]:
G

GameArray([[[9, 3, 8],
        [2, 6, 1],
        [7, 4, 5]],

       [[1, 4, 3],
        [6, 9, 7],
        [8, 2, 5]]])

In [10]:
hga = g.HalfGameArray(range(1,10))

In [11]:
print hga

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print hga.standard

[[9 7 8]
 [3 5 4]
 [6 2 1]]


In [13]:
hga == hga.standard

True

In [14]:
hgar = g.random_game().player(1)

In [15]:
hgar == hga

False

In [16]:
hgar.standard

HalfGameArray([[9, 8, 3],
       [2, 7, 4],
       [5, 1, 6]])

In [17]:
hga.standard

HalfGameArray([[9, 7, 8],
       [3, 5, 4],
       [6, 2, 1]])

In [40]:
gr = g.random_game()
G = g.GameArray(range(1,10) * 2)

In [19]:
G

GameArray([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
G.standard

GameArray([[[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]],

       [[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]]])

In [21]:
gr == G

False

In [22]:
gr

GameArray([[[2, 8, 1],
        [7, 6, 9],
        [3, 4, 5]],

       [[5, 8, 2],
        [9, 1, 3],
        [7, 6, 4]]])

In [23]:
LAZY_STRATEGY = range(1, 10)

LAZY_STRATEGY_HALF_GAME = g.HalfGameArray(LAZY_STRATEGY)
LAZY_STRATEGY_GAME = g.GameArray(LAZY_STRATEGY * 2)

In [24]:
lazy = LAZY_STRATEGY_GAME.copy()

In [25]:
standard_is = lazy.standard.view(np.ndarray)
standard_is

array([[[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]],

       [[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]]])

In [33]:
hgar.lehmer_int

81905

In [41]:
gr.lehmer_int

(25724, 6204)

In [44]:
for i in range(5):
    gr = g.random_game()
    %timeit gr.lehmer_int

10000 loops, best of 3: 51.9 µs per loop
10000 loops, best of 3: 53.4 µs per loop
10000 loops, best of 3: 52.7 µs per loop
10000 loops, best of 3: 51.9 µs per loop
10000 loops, best of 3: 50.4 µs per loop


In [48]:
import lukmdo_lehmer.lehmer as lehmer

lehmer.perm_from_int(range(1,10), 81905)

[6, 1, 2, 4, 7, 5, 8, 3, 9]

In [49]:
gr

GameArray([[[4, 3, 2],
        [8, 7, 6],
        [5, 1, 9]],

       [[3, 9, 4],
        [5, 1, 6],
        [8, 7, 2]]])

In [ ]:
for i in range(5):
    gr = g.random_game()
    %timeit g.lehmer_int_to_game(gr.lehmer_int)

10000 loops, best of 3: 108 µs per loop
10000 loops, best of 3: 108 µs per loop
10000 loops, best of 3: 108 µs per loop