In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import game2p3s as g

In [3]:
G = g.random_game()

In [4]:
print G

[[[5 9 6]
  [4 1 8]
  [7 2 3]]

 [[2 9 3]
  [6 4 5]
  [7 1 8]]]


In [5]:
G.standard

GameArray([[[9, 6, 5],
        [1, 8, 4],
        [2, 3, 7]],

       [[9, 3, 2],
        [4, 5, 6],
        [1, 8, 7]]])

In [6]:
print G.player(0).standard
print G.standard.player(0)

[[9 6 5]
 [1 8 4]
 [2 3 7]]
[[9 6 5]
 [1 8 4]
 [2 3 7]]


In [7]:
type(G.player(1))

game2p3s.HalfGameArray

In [8]:
G = G.standard

In [9]:
G

GameArray([[[9, 6, 5],
        [1, 8, 4],
        [2, 3, 7]],

       [[9, 3, 2],
        [4, 5, 6],
        [1, 8, 7]]])

In [10]:
hga = g.HalfGameArray(range(1,10))

In [11]:
print hga

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print hga.standard

[[9 7 8]
 [3 5 4]
 [6 2 1]]


In [13]:
hga == hga.standard

True

In [14]:
hgar = g.random_game().player(1)

In [15]:
hgar == hga

False

In [16]:
hgar.standard

HalfGameArray([[9, 4, 1],
       [3, 7, 2],
       [8, 5, 6]])

In [17]:
hga.standard

HalfGameArray([[9, 7, 8],
       [3, 5, 4],
       [6, 2, 1]])

In [18]:
gr = g.random_game()
G = g.GameArray(range(1,10) * 2)

In [19]:
G

GameArray([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
G.standard

GameArray([[[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]],

       [[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]]])

In [21]:
gr == G

False

In [22]:
gr

GameArray([[[1, 7, 4],
        [2, 5, 6],
        [9, 3, 8]],

       [[5, 4, 3],
        [1, 8, 9],
        [6, 2, 7]]])

In [23]:
LAZY_STRATEGY = range(1, 10)

LAZY_STRATEGY_HALF_GAME = g.HalfGameArray(LAZY_STRATEGY)
LAZY_STRATEGY_GAME = g.GameArray(LAZY_STRATEGY * 2)

In [24]:
lazy = LAZY_STRATEGY_GAME.copy()

In [25]:
standard_is = lazy.standard.view(np.ndarray)
standard_is

array([[[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]],

       [[9, 7, 8],
        [3, 5, 4],
        [6, 2, 1]]])

In [26]:
hgar.lehmer_int

141302

In [27]:
gr.lehmer_int

(304029, 175918)

In [28]:
for i in range(5):
    gr = g.random_game()
    %timeit gr.lehmer_int

10000 loops, best of 3: 52.2 µs per loop
10000 loops, best of 3: 51 µs per loop
10000 loops, best of 3: 52.5 µs per loop
10000 loops, best of 3: 50.5 µs per loop
10000 loops, best of 3: 51.4 µs per loop


In [29]:
import lukmdo_lehmer.lehmer as lehmer

lehmer.perm_from_int(range(1,10), 81905)

[6, 1, 2, 4, 7, 5, 8, 3, 9]

In [30]:
gr

GameArray([[[9, 6, 3],
        [2, 7, 8],
        [1, 4, 5]],

       [[3, 1, 2],
        [8, 6, 4],
        [7, 9, 5]]])

In [31]:
for i in range(5):
    gr = g.random_game()
    %timeit g.lehmer_int_to_game(gr.lehmer_int)

10000 loops, best of 3: 106 µs per loop
10000 loops, best of 3: 107 µs per loop
10000 loops, best of 3: 105 µs per loop
10000 loops, best of 3: 106 µs per loop
10000 loops, best of 3: 105 µs per loop
