In [1]:
import numpy as np

In [2]:
M = np.arange(9) + 1
np.random.shuffle(M)
M = M.reshape((3,3))

In [3]:
print M

[[4 7 8]
 [1 6 2]
 [3 5 9]]


In [4]:
roll_axes_by = np.unravel_index(M.argmax(), (3,3))

In [5]:
for axis, roll_by in enumerate(roll_axes_by):
    if roll_by:
        M = np.roll(M, -roll_by, axis=axis)
print M

[[9 3 5]
 [8 4 7]
 [2 1 6]]


In [6]:
S = M[1:, 1:]
print S

[[4 7]
 [1 6]]


In [7]:
roll_sub_axes_by = np.unravel_index(S.argmax(), (2,2))

In [8]:
for axis, roll_by in enumerate(roll_sub_axes_by):
    if roll_by:
        S = np.roll(S, 1, axis=axis)
M[1:, 1:] = S

In [9]:
print M

[[9 3 5]
 [8 7 4]
 [2 6 1]]


In [10]:
np.argmax(M)

0